COMFORTABLE_ACTIONS = {
    0: 'IDLE',
    1: 'DECAY_STEERING_MAINTAIN_SPEED',
    2: 'DECAY_STEERING_DECREASE_SPEED',
    3: 'DECAY_STEERING_INCREASE_SPEED',
    4: 'SMALL_STEER_LEFT_MAINTAIN_SPEED',
    5: 'SMALL_STEER_LEFT_DECREASE_SPEED',
    6: 'SMALL_STEER_LEFT_INCREASE_SPEED',
    7: 'SMALL_STEER_RIGHT_MAINTAIN_SPEED',
    8: 'SMALL_STEER_RIGHT_DECREASE_SPEED',
    9: 'SMALL_STEER_RIGHT_INCREASE_SPEED',
    10: 'LARGE_STEER_LEFT_MAINTAIN_SPEED',
    11: 'LARGE_STEER_LEFT_DECREASE_SPEED',
    12: 'LARGE_STEER_LEFT_INCREASE_SPEED',
    13: 'LARGE_STEER_RIGHT_MAINTAIN_SPEED',
    14: 'LARGE_STEER_RIGHT_DECREASE_SPEED',
    15: 'LARGE_STEER_RIGHT_INCREASE_SPEED',
    # TODO: Maintain speed (PID) * steer(decay, LR small steer, LR large steer)
    # TODO: Decrease speed comfort (PID) * steer(decay, LR small steer, LR large steer) - brake + 0 accel
    # TODO: Increase speed comfort (PID) * steer(decay, LR small steer, LR large steer)
    # Total safe = 5 steer * 3 accel + idle = 16

    # TODO: Increase speed (max without losing traction)
    # TODO: Brake emergency stop
}

COMFORTABLE_ACTIONS_IDLE = 0
COMFORTABLE_ACTIONS_MAINTAIN_SPEED = {1, 4, 7, 10, 13}
COMFORTABLE_ACTIONS_DECREASE_SPEED = {2, 5, 8, 11, 14}
COMFORTABLE_ACTIONS_INCREASE_SPEED = {3, 6, 9, 12, 15}
COMFORTABLE_ACTIONS_DECAY_STEERING = {1, 2, 3}
COMFORTABLE_ACTIONS_SMALL_STEER_LEFT = {4, 5, 6}
COMFORTABLE_ACTIONS_SMALL_STEER_RIGHT = {7, 8, 9}
COMFORTABLE_ACTIONS_LARGE_STEER_LEFT = {10, 11, 12}
COMFORTABLE_ACTIONS_LARGE_STEER_RIGHT = {13, 14, 15}
COMFORTABLE_ACTIONS_LARGE_STEER = COMFORTABLE_ACTIONS_LARGE_STEER_LEFT | COMFORTABLE_ACTIONS_LARGE_STEER_RIGHT